Now you should run one of the following depending on your shell
source /share/apps/python/anaconda3.2019.3/etc/profile.d/conda.sh
source /share/apps/python/anaconda3.2019.3/etc/profile.d/conda.csh
Traceback (most recent call last):
  File "Model/Main.py", line 9, in <module>
    from utility.batch_test import *
  File "/qfs/people/hamc649/recommendation/knowledge_graph_attention_network/Model/utility/batch_test.py", line 42, in <module>
    data_generator = KGAT_loader(args=args, path=args.data_path + args.dataset)
  File "/qfs/people/hamc649/recommendation/knowledge_graph_attention_network/Model/utility/loader_kgat.py", line 16, in __init__
    super().__init__(args, path)
  File "/qfs/people/hamc649/recommendation/knowledge_graph_attention_network/Model/utility/load_data.py", line 27, in __init__
    self.train_data, self.train_user_dict = self._load_ratings(train_file)
  File "/qfs/people/hamc649/recommendation/knowledge_graph_attention_network/Model/utility/load_data.py", line 46, in _load_ratings
    lines = open(file_name, 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '../Data/yelp2018/train.txt'
/tmp/slurmd/job379490/slurm_script: line 30: --lr: command not found
